### ISSUE TITLE
Fix: HTML Validation Errors

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-Krowno04#2]
Hi @Krowno04 

Absolutely awesome submission for Assignment 02 🎉! Well done.

## Issue Description

I ran your code through the HTML Validator and there are a couple of errors being thrown.

If you would like to take some additional time to address these small items, or make any further tweaks to your page, you may make changes to your code for the the next 72 hours without penalty.

## HTML Validator Results

Here is the link to the full results:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-Krowno04

## Screenshot

<img width="1569" alt="Screenshot 2023-02-20 at 12 11 25 PM" src="https://user-images.githubusercontent.com/9325038/220167277-719272a1-e773-4752-a7dc-a83b412936c9.png">

**Comment by Krowno04** [comment]
I went through and fixed all those errors, so the validator now shows no issues for the HTML file! Thanks for letting me know and giving me time to fix them!

**Comment by neilmispelaar** [comment]
Yay!

Absolutely. And awesome sauce. Truly well done.

This paradigm of iterative development (build -> review -> fix -> learn) is actually closer to how projects are run in industry.

If I spot anything else I'll let you know.

**Comment by neilmispelaar** [comment]
Just to confirm - you saw issue #3
